WIP: fact_diff filter plugin
ansible-collections/ansible.utils pull request #310
Opened 2023-11-02 14:08 UTC by ashwini-mhatre

##### SUMMARY

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2023-11-07 14:23 UTC, NilashishC requested changes
Please fix the lint issues before merging this PR.

2023-11-08 01:18 UTC, rohitthakur2590 requested changes

2023-11-08 01:18 UTC, rohitthakur2590 commented on plugins/filter/fact_diff.py
> +
are multiple new lines required here ?

2023-11-08 01:18 UTC, rohitthakur2590 commented on plugins/filter/fact_diff.py
> +    author: Ashwini Mhatre ((@amhatre))
are these multiple braces intended?

2023-11-08 01:18 UTC, rohitthakur2590 commented on plugins/filter/fact_diff.py
> +"""
examples are missing

2023-11-09 16:01 UTC, rohitthakur2590 approved these changes

2023-11-10 06:30 UTC, NilashishC commented on plugins/filter/fact_diff.py
> +                            description:
Indentation issue here.

2023-11-10 06:31 UTC, NilashishC commented on plugins/filter/fact_diff.py
> +    notes:
Is this required?

2023-11-10 06:32 UTC, NilashishC commented on plugins/filter/fact_diff.py
> +    res = str(res)
Please use to_text() here.

2023-11-10 06:32 UTC, NilashishC commented on plugins/filter/fact_diff.py
> +    import json
Is this import required?

2023-11-10 11:20 UTC, NilashishC approved these changes

2023-11-13 05:58 UTC, merged