add wildcard mask/hostmask to ipaddr filter doc page
ansible-collections/ansible.utils pull request #324
Opened 2024-01-10 12:29 UTC by fizmata

##### SUMMARY
add wildcard mask/hostmask to ipaddr filter doc page

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
ipaddr filter doc page

##### ADDITIONAL INFORMATION
This might seem like an unnecessary addition but wildcard filter not being here has cost me couple of hours and a failed exam. I tried to follow convention as much as I could. I'll be glad if I help other avoid such fate.

2024-07-17 19:08 UTC, Ruchip16 approved these changes

2024-07-19 12:01 UTC, NilashishC approved these changes

2024-07-19 12:24 UTC, NilashishC approved these changes

2024-07-19 12:58 UTC, KB-perByte requested changes
Just making the changelog more clear.

2024-07-19 12:58 UTC, KB-perByte commented on changelogs/fragments/324.yaml
> +  - Add a wildcard mask/hostmask documentation to ipaddr filter doc page on how to obtain the wildcard mask/hostmask of an IP address.
```suggestion
  - Add a wildcard mask/hostmask documentation to ipaddr filter doc page to obtain an IP address's wildcard mask/hostmask.
```

2024-07-19 14:31 UTC, KB-perByte approved these changes

2024-07-19 14:43 UTC, merged