Fix nightly runs
ansible-collections/ansible.utils pull request #334
Opened 2024-02-14 09:09 UTC by ashwini-mhatre

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below

```

2024-02-14 10:04 UTC, NilashishC commented on test-requirements.txt
>  git+https://github.com/ansible-network/pytest-ansible-network-integration.git
Unrelated, but can you please fix the pytest-ansible requirements in this collection as well?

2024-02-14 12:24 UTC, NilashishC commented on test-requirements.txt
>  git+https://github.com/ansible-network/pytest-ansible-network-integration.git
Same as above.

2024-02-14 23:00 UTC, doc-sheet commented
Hi! I suppose it could be better to just pin to `<=1.0.0` because in some environments netaddr is way older then 0.10.1

2024-02-16 06:39 UTC, NilashishC requested changes
Current changes look good. But seems like new lint failures have shown up. We'll need to fix that.

2024-02-16 09:25 UTC, NilashishC approved these changes

2024-02-16 10:19 UTC, merged