using regex for path split
ansible-collections/ansible.utils pull request #368
Opened 2024-08-21 10:09 UTC by eberna

##### SUMMARY

Fixes #349

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

ansible.utils.update_fact
##### ADDITIONAL INFORMATION

If a key in the path contains a square bracket the module does not separate the path correctly and if fails. This request changes the parser part to use regular expressions. 

```
ansible@lnx-controller:~/ansible_collections/ansible/utils$ ansible-playbook -vv  main.yaml
ansible-playbook [core 2.16.3]
  config file = /home/ansible/ansible_collections/ansible/utils/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/ansible_collections
  executable location = /home/ansible/.local/bin/ansible-playbook
  python version = 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] (/home/ansible/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /home/ansible/ansible_collections/ansible/utils/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]collections_paths option, does not fit var naming standard, use the singular form collections_path instead. This feature
 will be removed from ansible-core in version 2.19. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
running playbook inside collection ansible.utils
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: main.yaml **************************************************************************************************************************************
1 plays in main.yaml

PLAY [127.0.0.1] *****************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:1
ok: [127.0.0.1]

TASK [set fact] ******************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:4
ok: [127.0.0.1] => {"ansible_facts": {"my_dict": {"[runners]": "old value"}}, "changed": false}

TASK [update fact] ***************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:8
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: '[runners'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error: the key '[runners' was not found in {'[runners]': 'old value'}."}

PLAY RECAP ***********************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

ansible@lnx-controller:~/ansible_collections/ansible/utils$ ansible-playbook -vv  main.yaml
ansible-playbook [core 2.16.3]
  config file = /home/ansible/ansible_collections/ansible/utils/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ansible/ansible_collections
  executable location = /home/ansible/.local/bin/ansible-playbook
  python version = 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] (/home/ansible/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
Using /home/ansible/ansible_collections/ansible/utils/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]collections_paths option, does not fit var naming standard, use the singular form collections_path instead. This feature
 will be removed from ansible-core in version 2.19. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
running playbook inside collection ansible.utils
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: main.yaml **************************************************************************************************************************************
1 plays in main.yaml

PLAY [127.0.0.1] *****************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:1
ok: [127.0.0.1]

TASK [set fact] ******************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:4
ok: [127.0.0.1] => {"ansible_facts": {"my_dict": {"[runners]": "old value"}}, "changed": false}

TASK [update fact] ***************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:8
changed: [127.0.0.1] => {"changed": true, "my_dict": {"[runners]": "new value"}}

TASK [debug] *********************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:15
ok: [127.0.0.1] => {
    "my_dict": {
        "[runners]": "old value"
    }
}

TASK [debug] *********************************************************************************************************************************************
task path: /home/ansible/ansible_collections/ansible/utils/main.yaml:16
ok: [127.0.0.1] => {
    "updated": {
        "changed": true,
        "failed": false,
        "my_dict": {
            "[runners]": "new value"
        }
    }
}

PLAY RECAP ***********************************************************************************************************************************************
127.0.0.1                  : ok=5    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
Hope this may help, thank you.

2024-08-28 10:02 UTC, Ruchip16 commented
@eberna can you please add specific tests as well to validate the change?

2024-08-28 10:24 UTC, eberna commented
> @eberna can you please add specific tests as well to validate the change?

Integration or unit test? or both? 
thanks

2024-08-28 17:43 UTC, Ruchip16 commented
> > @eberna can you please add specific tests as well to validate the change?
> 
> Integration or unit test? or both? thanks

I am fine with both or anything that would validate this particular change.

2024-09-12 12:38 UTC, eberna commented
> > > @eberna can you please add specific tests as well to validate the change?
> > 
> > 
> > Integration or unit test? or both? thanks
> 
> I am fine with both or anything that would validate this particular change.

done, I hope it's okay, in case let me know and I'll edit.

2025-03-21 10:58 UTC, Ruchip16 commented on plugins/action/update_fact.py
> +        regex = re.compile(r"^[^\[\].]+|^\[[\'\"].+?[\'\"]\]|^\[.+?\]")
@eberna any particular reason for adding regex here instead of the existing code behaviour?

2025-03-21 11:07 UTC, Ruchip16 commented
pre-commit.ci autofix

2025-03-21 17:20 UTC, eberna commented on plugins/action/update_fact.py
> +        regex = re.compile(r"^[^\[\].]+|^\[[\'\"].+?[\'\"]\]|^\[.+?\]")
If a key in the path contains a square bracket the module does not separate the path correctly and if fails. This request changes the parser part to use regular expressions.

2026-05-28 09:01 UTC, TheNova22 requested changes

2026-05-28 09:01 UTC, TheNova22 commented on plugins/action/update_fact.py
> +        regex = re.compile(r"^[^\[\].]+|^\[[\'\"].+?[\'\"]\]|^\[.+?\]")
Doesnt branch 3 (`^\[.+?\]`) and branch 2 covers similar cases? (`^\[[\'\"].+?[\'\"]\]`)

Branch 3 seems like superset of branch 2. So can branch 2 be removed in that case?
Branch 2 matches - ['key1'], ["key2"]
Branch 3 matches - [key0],['key1'], ["key2"]

2026-05-28 09:01 UTC, TheNova22 commented on tests/integration/targets/utils_update_fact/tasks/main.yaml
> +        d:
Can some more complicated/edge cases be added, just to ensure no future change breaks it.
Example:
```
    - name: Set a fact with multiple bracket variations
      ansible.builtin.set_fact:
        bracket_edge_cases:
          "[[double]]": value1
          "]]right]]": value2
          "[prefix": value3
          "suffix]": value4
          "{curlies}": value 5
          "[parent]":
            - regular:
                "[bracket]": value6
    - name: update fact
      ansible.utils.update_fact:
        updates:
          - path: bracket_edge_cases["[[double]]"]
            value: "newval1"
          - path: bracket_edge_cases["]]right]]"]
            value: "newval2"
          - path: bracket_edge_cases["[prefix"]
            value: "newval3"
          - path: bracket_edge_cases["suffix]"]
            value: "newval4"
          - path: bracket_edge_cases["{curlies}"]
            value: "newval5"
          - path: bracket_edge_cases["[parent]"][0]["regular"]["[bracket]"]
            value: "newval6"
```

2026-05-28 09:49 UTC, eberna commented on plugins/action/update_fact.py
> +        regex = re.compile(r"^[^\[\].]+|^\[[\'\"].+?[\'\"]\]|^\[.+?\]")
Branch 2 covers exactly what the issues was, the presence of brackets inside the quotes like:
['tes[]t1']['test2']
['tes]t1'][test2]
['tes[t1'].test2

Since some time has passed since i wrote it, i tested it again: https://regex101.com/r/qDRrV4/1
This one does not look to me a valid list: [key0],'key1'], ["key2"], also it does not covers nested lists but as far i remember neither did before. Thanks :-)

2026-05-28 10:04 UTC, TheNova22 commented on plugins/action/update_fact.py
> +        regex = re.compile(r"^[^\[\].]+|^\[[\'\"].+?[\'\"]\]|^\[.+?\]")
Oh thanks! It's a typo from my end, it should be: 
> Branch 3 matches - [key0],['key1'], ["key2"]

And that is right, nested scenario and even the base case wasn't covered before 
Thanks for clearing it for me! :) 
Please check on the other comment to add some edge cases like the one mentioned here. Marking this comment as resolved.

2026-05-28 13:36 UTC, eberna commented on tests/integration/targets/utils_update_fact/tasks/main.yaml
> +        d:
Added more tests as requested, thank for the review!

2026-05-28 13:55 UTC, TheNova22 commented on tests/integration/targets/utils_update_fact/tasks/main.yaml
> +        d:
Yay, thanks for looking into it and making this change @eberna! :rocket:

2026-05-28 13:56 UTC, TheNova22 approved these changes

2026-06-05 07:55 UTC, rohitthakur2590 approved these changes

2026-06-05 07:56 UTC, rohitthakur2590 commented
@eberna  thank you for your valuable contribution.

2026-06-05 07:56 UTC, merged