Added IP test plugins
ansible-collections/ansible.utils pull request #60
Opened 2021-03-30 04:22 UTC by priyamsahoo

##### SUMMARY

This PR adds 24 IP test plugins along with their unit tests

##### ISSUE TYPE

- New Plugins Pull Request

##### COMPONENT NAME

1. in_any_network
2. in_network
3. in_one_network
4. ip_address
5. ip
6. ipv4
7. ipv4_address
8. ipv4_hostmask
9. ipv4_netmask
10. ipv6
11. ipv6_address
12. ipv6_ipv4_mapped
13. ipv6_sixtofour
14. ipv6_teredo
15. loopback
16. mac
17. multicast
18. private
19. public
20. reserved
21. subnet_of
22. supernet_of
23. unspecified
24. resolvable
##### ADDITIONAL INFORMATION

```paste below

```

2021-03-31 13:37 UTC, Qalthos requested changes

2021-03-31 13:37 UTC, Qalthos commented on README.md
> +[ansible.utils.validate](https://github.com/ansible-collections/ansible.utils/blob/network-test-plugins/docs/ansible.utils.validate_filter.rst)|Validate data with provided criteria
The branch should not have changed here

2021-04-01 05:50 UTC, priyamsahoo commented on README.md
> +[ansible.utils.validate](https://github.com/ansible-collections/ansible.utils/blob/network-test-plugins/docs/ansible.utils.validate_filter.rst)|Validate data with provided criteria
This is resolved in eb13cfb.

2021-04-22 11:39 UTC, ashwini-mhatre commented
@priyamsahoo check pipeline is failing can you please fix the issues?

2021-04-22 13:55 UTC, ganeshrn reviewed
Can you please split the single big PR into multiple PR's so that it is bit easier to review and tack changes. Also I can see some files  completely commented out for eg: `plugins/test/general.py`. If it is not required those files can be removed

2021-05-17 10:48 UTC, closed without merging

2021-05-17 10:49 UTC, ashwini-mhatre commented
The code changes are already merged so closing this